name: Test Deploy to Playstore

on:
    push:
      tags:
        - 'v*.[0-99]'

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Tag Release
        run: |
          version_name=${GITHUB_REF##*/}
          echo "Tagging release with tag $version_name"
          git tag $version_name
          git push origin --tags
